# Generated by Django 2.2.6 on 2019-10-23 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customerRequestId', models.CharField(max_length=40, null=True)),
                ('customerName', models.CharField(max_length=40, null=True)),
                ('customerEmailId', models.EmailField(blank=True, max_length=254, unique=True)),
                ('customerMcafeeEmailId', models.EmailField(blank=True, max_length=254, unique=True)),
            ],
        ),
    ]
